version: '3.8'

services:
  # The single production service
  server:
    build:
      # The context is the project root so the Dockerfile can access ./client
      context: .
      dockerfile: ./server/Dockerfile
      # Target the final 'runner' stage for a lean production image
      target: runner
    container_name: e-shop-server-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    # Mount certificates read-only.
    volumes:
      - ./server/certs:/app/certs:ro
    # This allows the container to connect to your local MariaDB on the host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - e-shop-net

# Define the network
networks:
  e-shop-net:
    driver: bridge