version: '3.8'

services:
  # The Backend Server Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: e-shop-server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/certs:/app/certs:ro
    # This allows the container to connect to your local MariaDB on the host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - e-shop-net

  # The Frontend Client Service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: e-shop-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./client/certs:/app/certs:ro
    environment:
      # Ensures hot-reloading works reliably inside the container
      - CHOKIDAR_USEPOLLING=1
    networks:
      - e-shop-net
    # This ensures the server starts before the client
    depends_on:
      - server

# Define the network that allows containers to communicate by name
networks:
  e-shop-net:
    driver: bridge